### ISSUE TITLE
Bulk Number Verification

### ISSUE THREAD

**Issue by Dnymte** [AbhishekBiswal/whatsapp-verify#2]
Hello, Abhishek, great work by the way among all the other scripts I tried this one is the fastest and reliable. 

I just have one question as Iam not expert with JavaScript that much, how to use the bulk number functionality ? I tried replacing the directory for the checkNumber.js with the checkNumberBulk.js but I am guessing that's not the right way, do you mind if you guided me on how to use it ?

**Comment by AbhishekBiswal** [comment]
@Dnymte this repository doesn't yet have a script to bulk check the numbers but the command can be used to write a bash script to check one number after another.

Something like

```
declare -a arr=("NUMBER1" "NUMBER2" "NUMBER3")

for i in "${arr[@]}"
do
   npm run check $i
done
```
